### ISSUE TITLE
[3.1.5] AttributeError: 'NoneType' object has no attribute 'decode' when running COPY ... FROM STDIN

### ISSUE THREAD

**Issue by char101** [psycopg/psycopg#460]
Hi,

I got this exception when running a `COPY ... FROM STDIN` query with version 3.1.5.

```
File "C:\python\3.11\Lib\site-packages\psycopg\cursor.py", line 903, in copy
    self._conn.wait(self._start_copy_gen(statement, params))
  File "C:\python\3.11\Lib\site-packages\psycopg\connection.py", line 957, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "psycopg_binary\\_psycopg/waiting.pyx", line 193, in psycopg_binary._psycopg.wait_c
  File "C:\python\3.11\Lib\site-packages\psycopg\cursor.py", line 417, in _start_copy_gen
    self._select_current_result(0)
  File "C:\python\3.11\Lib\site-packages\psycopg\cursor.py", line 530, in _select_current_result
    self._make_row = self._make_row_maker()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\3.11\Lib\site-packages\psycopg\cursor.py", line 709, in _make_row_maker
    return self._row_factory(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\3.11\Lib\site-packages\psycopg\rows.py", line 145, in namedtuple_row
    nt = _make_nt(cursor._encoding, *(res.fname(i) for i in range(nfields)))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\3.11\Lib\site-packages\psycopg\rows.py", line 151, in _make_nt
    snames = tuple(_as_python_identifier(n.decode(enc)) for n in names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\3.11\Lib\site-packages\psycopg\rows.py", line 151, in <genexpr>
    snames = tuple(_as_python_identifier(n.decode(enc)) for n in names)
                                         ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'decode'
```

The same code works with 3.1.4.

**Comment by char101** [comment]
Environment:

OS: Windows 10
Postgresql 14.6
Python 3.11.1

The code is something like this

```python
with curr.copy('copy table (columns) from stdin') as copy:
  for row in data:
    copy.write_row(row)
```

**Comment by dvarrazzo** [comment]
Thank you for the report. Will release a bugfix release immediately

**Comment by dvarrazzo** [comment]
Psycopg 3.1.6 released to solve this regression. Sorry about the inconvenience!

**Comment by char101** [comment]
Thank you for the quick update.
